### ISSUE TITLE
Lost addon in appdata roaming folder after pressing reload

### ISSUE THREAD

**Issue by NewMediaSupply** [karmaral/addon-reloader#1]
I worked on an addon the past three days which was installed as a normal addon in Blender Foundation\Blender\2.91\scripts\addons. But not in a folder, so a single .py file no __init__.py. 
When giving up the location of the file, and press reload, I got an error message something like "the file is in the path where ...."
Then the file is gone from the Blender Foundation\Blender\2.91\scripts\addons directory, can't find it.

**Comment by karmaral** [comment]
I'm really sorry to hear that. I've never experienced something like that, and from what I remember, the addon doesn't do any writing of the files in the directories, it merely reads them, so perhaps this was a different issue.

What did the error message say exactly?
Maybe Blender replaced a file in the internal addon directory (\scripts\addons) when reinstalling your script? I'm not sure, I'd need more information. Did the file got saved in your .blend file at least?

Perhaps developing directly from the \scripts\addons is not the most safe practice. I usually have a workspace folder and only formally install an addon where it's supposed to go when using a release version. I don't know if it makes a difference, but it helps as precaution.

If you can provide me with a bit more info, maybe we can figure it out.

**Comment by NewMediaSupply** [comment]
Ah I see, thanks. It was a little bit of panic, but it's ok now; luckily the textfile was still in Blender. I will try with another location later and if the problem comes back I'll let you know. And I should always make a backup.  
I don't have the error message here, but if I see it, I keep you up to date.
